# Generated by Django 3.2.15 on 2022-08-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0018_auto_20220819_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='headoffice',
            name='country_eng',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
