# Generated by Django 3.2.15 on 2022-08-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0019_headoffice_country_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='headoffice',
            name='export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headoffice',
            name='korea',
            field=models.BooleanField(default=False),
        ),
    ]
